name: Update screenshots

on:
  push:
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Run screenshotter container
      run: docker run -v $(pwd):/app ghcr.io/gokarna-theme/gokarna-hugo/screenshotter

    - name: See diffs
      run: |
        if [[ -z $(git status images --porcelain) ]]; then
          echo "No changes found"
          exit 0
        fi

        gh pr create -B main -H auto-update-screenshots --title 'chore: update screenshots' --body 'Created by Github action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
