name: 'Close stale issues and mark inactive PRs'
on:
  schedule:
    - cron: '0 0 * * 0'  # At 00:00 on every Sunday

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open for 90 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          stale-pr-message: 'This PR is stale because it has been open for 90 days with no activity.'
          close-issue-message: 'This issue was closed due to inactivity'
          days-before-stale: 90
          days-before-close: 30
          days-before-pr-close: -1
          exempt-all-assignees: true
